/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import presentacion.Catálogos.Clientes.FrmCatalogoClientes;
import presentacion.Catálogos.FrmCatalogoFunciones;
import presentacion.Catálogos.FrmCatalogoPeliculas;
import presentacion.Catálogos.FrmCatalogoSalas;
import presentacion.Reportes.FrmReportes;

/**
 *
 * @author nomar
 */
public class FrmMenuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form FrmInicioSesion
     */
    public FrmMenuAdmin() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_continuar1 = new javax.swing.JLabel();
        btn_continuar1 = new javax.swing.JPanel();
        lbl_continuar2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        fondoTablas = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        btn_Reportes = new javax.swing.JPanel();
        lbl_cPeliculas3 = new javax.swing.JLabel();
        btn_close = new javax.swing.JPanel();
        close_icon = new javax.swing.JLabel();
        btn_cSalas = new javax.swing.JPanel();
        lbl_cSalas = new javax.swing.JLabel();
        btn_cPeliculas = new javax.swing.JPanel();
        lbl_cPeliculas = new javax.swing.JLabel();
        btn_cClientes = new javax.swing.JPanel();
        lbl_cClientes = new javax.swing.JLabel();
        btn_cFunciones = new javax.swing.JPanel();
        lbl_cFunciones = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblfondoTabla = new javax.swing.JLabel();
        lbl_cPeliculas1 = new javax.swing.JLabel();
        btnRegresar3 = new javax.swing.JPanel();
        Regresar3 = new javax.swing.JLabel();
        fondoEncabezado6 = new javax.swing.JLabel();
        background_img = new javax.swing.JLabel();

        lbl_continuar1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_continuar1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_continuar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_continuar1.setText("Catálogo Salas");

        btn_continuar1.setBackground(new java.awt.Color(83, 85, 96));

        lbl_continuar2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_continuar2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_continuar2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_continuar2.setText("Catálogo Salas");

        javax.swing.GroupLayout btn_continuar1Layout = new javax.swing.GroupLayout(btn_continuar1);
        btn_continuar1.setLayout(btn_continuar1Layout);
        btn_continuar1Layout.setHorizontalGroup(
            btn_continuar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_continuar1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lbl_continuar2, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                .addContainerGap())
        );
        btn_continuar1Layout.setVerticalGroup(
            btn_continuar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_continuar1Layout.createSequentialGroup()
                .addComponent(lbl_continuar2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel1.setText("jLabel1");

        fondoTablas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondoTablas.png"))); // NOI18N
        fondoTablas.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cinepolis App");
        setUndecorated(true);
        setResizable(false);

        content.setBackground(new java.awt.Color(47, 48, 55));
        content.setForeground(new java.awt.Color(255, 255, 255));
        content.setMinimumSize(new java.awt.Dimension(800, 600));
        content.setPreferredSize(new java.awt.Dimension(800, 600));
        content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Reportes.setBackground(new java.awt.Color(83, 85, 96));
        btn_Reportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Reportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ReportesMouseClicked(evt);
            }
        });

        lbl_cPeliculas3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_cPeliculas3.setForeground(new java.awt.Color(255, 255, 255));
        lbl_cPeliculas3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_cPeliculas3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnReportes.png"))); // NOI18N

        javax.swing.GroupLayout btn_ReportesLayout = new javax.swing.GroupLayout(btn_Reportes);
        btn_Reportes.setLayout(btn_ReportesLayout);
        btn_ReportesLayout.setHorizontalGroup(
            btn_ReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_cPeliculas3, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );
        btn_ReportesLayout.setVerticalGroup(
            btn_ReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_ReportesLayout.createSequentialGroup()
                .addComponent(lbl_cPeliculas3)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        content.add(btn_Reportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, 210, 80));

        btn_close.setBackground(new java.awt.Color(47, 48, 55));
        btn_close.setForeground(new java.awt.Color(47, 48, 55));
        btn_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_close.setPreferredSize(new java.awt.Dimension(20, 20));
        btn_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_closeMouseClicked(evt);
            }
        });
        btn_close.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close_icon.png"))); // NOI18N
        btn_close.add(close_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 0, 20, 20));

        content.add(btn_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 20, 20));

        btn_cSalas.setBackground(new java.awt.Color(83, 85, 96));
        btn_cSalas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cSalas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cSalasMouseClicked(evt);
            }
        });

        lbl_cSalas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_cSalas.setForeground(new java.awt.Color(255, 255, 255));
        lbl_cSalas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_cSalas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnCatalogoSalas.png"))); // NOI18N

        javax.swing.GroupLayout btn_cSalasLayout = new javax.swing.GroupLayout(btn_cSalas);
        btn_cSalas.setLayout(btn_cSalasLayout);
        btn_cSalasLayout.setHorizontalGroup(
            btn_cSalasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_cSalasLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_cSalas))
        );
        btn_cSalasLayout.setVerticalGroup(
            btn_cSalasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_cSalasLayout.createSequentialGroup()
                .addComponent(lbl_cSalas)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        content.add(btn_cSalas, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 200, 80));

        btn_cPeliculas.setBackground(new java.awt.Color(83, 85, 96));
        btn_cPeliculas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cPeliculas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cPeliculasMouseClicked(evt);
            }
        });

        lbl_cPeliculas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_cPeliculas.setForeground(new java.awt.Color(255, 255, 255));
        lbl_cPeliculas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_cPeliculas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnCatalogoPeliculas.png"))); // NOI18N

        javax.swing.GroupLayout btn_cPeliculasLayout = new javax.swing.GroupLayout(btn_cPeliculas);
        btn_cPeliculas.setLayout(btn_cPeliculasLayout);
        btn_cPeliculasLayout.setHorizontalGroup(
            btn_cPeliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_cPeliculasLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_cPeliculas))
        );
        btn_cPeliculasLayout.setVerticalGroup(
            btn_cPeliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_cPeliculasLayout.createSequentialGroup()
                .addComponent(lbl_cPeliculas)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        content.add(btn_cPeliculas, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 200, 80));

        btn_cClientes.setBackground(new java.awt.Color(83, 85, 96));
        btn_cClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cClientesMouseClicked(evt);
            }
        });

        lbl_cClientes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_cClientes.setForeground(new java.awt.Color(255, 255, 255));
        lbl_cClientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_cClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnCatalogoClientes.png"))); // NOI18N
        lbl_cClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btn_cClientesLayout = new javax.swing.GroupLayout(btn_cClientes);
        btn_cClientes.setLayout(btn_cClientesLayout);
        btn_cClientesLayout.setHorizontalGroup(
            btn_cClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_cClientesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_cClientes))
        );
        btn_cClientesLayout.setVerticalGroup(
            btn_cClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_cClientesLayout.createSequentialGroup()
                .addComponent(lbl_cClientes)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        content.add(btn_cClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 200, 80));

        btn_cFunciones.setBackground(new java.awt.Color(83, 85, 96));
        btn_cFunciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cFunciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cFuncionesMouseClicked(evt);
            }
        });

        lbl_cFunciones.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_cFunciones.setForeground(new java.awt.Color(255, 255, 255));
        lbl_cFunciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_cFunciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnCatalogoFunciones.png"))); // NOI18N
        lbl_cFunciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btn_cFuncionesLayout = new javax.swing.GroupLayout(btn_cFunciones);
        btn_cFunciones.setLayout(btn_cFuncionesLayout);
        btn_cFuncionesLayout.setHorizontalGroup(
            btn_cFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_cFuncionesLayout.createSequentialGroup()
                .addComponent(lbl_cFunciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        btn_cFuncionesLayout.setVerticalGroup(
            btn_cFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_cFunciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        content.add(btn_cFunciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 200, 80));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cinépolis");
        content.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        lblfondoTabla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondoTablas.png"))); // NOI18N
        content.add(lblfondoTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 790, 500));

        lbl_cPeliculas1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_cPeliculas1.setForeground(new java.awt.Color(255, 0, 51));
        lbl_cPeliculas1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_cPeliculas1.setText("Administrador");
        content.add(lbl_cPeliculas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 800, 20));

        btnRegresar3.setBackground(new java.awt.Color(47, 48, 55));
        btnRegresar3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresar3MouseClicked(evt);
            }
        });
        btnRegresar3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Regresar3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Regresar3.setForeground(new java.awt.Color(255, 255, 255));
        Regresar3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Regresar3.setText("<");
        Regresar3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar3.add(Regresar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -5, 20, 20));

        content.add(btnRegresar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 20, 20));

        fondoEncabezado6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EncabezadoBackground.png"))); // NOI18N
        content.add(fondoEncabezado6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, -1));

        background_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.png"))); // NOI18N
        background_img.setMaximumSize(new java.awt.Dimension(815, 600));
        background_img.setPreferredSize(new java.awt.Dimension(815, 600));
        content.add(background_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseClicked
        dispose();
    }//GEN-LAST:event_btn_closeMouseClicked

    private void btn_cClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cClientesMouseClicked
        // Abre frame Catálogo Clientes
        new FrmCatalogoClientes().setVisible(true);
        this.dispose();  
    }//GEN-LAST:event_btn_cClientesMouseClicked

    private void btn_cFuncionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cFuncionesMouseClicked
        // Abre frame Catálogo Funciones
        new FrmCatalogoFunciones().setVisible(true);
        this.dispose();  
    }//GEN-LAST:event_btn_cFuncionesMouseClicked

    private void btn_cSalasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cSalasMouseClicked
        // Abre frame Catálogo Salas
        new FrmCatalogoSalas().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_cSalasMouseClicked

    private void btn_cPeliculasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cPeliculasMouseClicked
        // Abre frame Catálogo Películas
        new FrmCatalogoPeliculas().setVisible(true);
        this.dispose();        
    }//GEN-LAST:event_btn_cPeliculasMouseClicked

    private void btn_ReportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ReportesMouseClicked
        // Abre frame Reportes
        new FrmReportes().setVisible(true);
        this.dispose();   
    }//GEN-LAST:event_btn_ReportesMouseClicked

    private void btnRegresar3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresar3MouseClicked
        // TODO add your handling code here:
        new FrmInicioSesion().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresar3MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Regresar2;
    private javax.swing.JLabel Regresar3;
    private javax.swing.JLabel background_img;
    private javax.swing.JPanel btnRegresar2;
    private javax.swing.JPanel btnRegresar3;
    private javax.swing.JPanel btn_Reportes;
    private javax.swing.JPanel btn_cClientes;
    private javax.swing.JPanel btn_cFunciones;
    private javax.swing.JPanel btn_cPeliculas;
    private javax.swing.JPanel btn_cSalas;
    private javax.swing.JPanel btn_close;
    private javax.swing.JPanel btn_continuar1;
    private javax.swing.JLabel close_icon;
    private javax.swing.JPanel content;
    private javax.swing.JLabel fondoEncabezado6;
    private javax.swing.JLabel fondoTablas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbl_cClientes;
    private javax.swing.JLabel lbl_cFunciones;
    private javax.swing.JLabel lbl_cPeliculas;
    private javax.swing.JLabel lbl_cPeliculas1;
    private javax.swing.JLabel lbl_cPeliculas3;
    private javax.swing.JLabel lbl_cSalas;
    private javax.swing.JLabel lbl_continuar1;
    private javax.swing.JLabel lbl_continuar2;
    private javax.swing.JLabel lblfondoTabla;
    // End of variables declaration//GEN-END:variables
}
