/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion.Catálogos;

import presentacion.*;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;

/**
 *
 * @author nomar
 */
public class FrmCatálogoSalas extends javax.swing.JFrame {

    /**
     * Creates new form FrmInicioSesion
     */
    public FrmCatálogoSalas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_continuar1 = new javax.swing.JLabel();
        btn_continuar1 = new javax.swing.JPanel();
        lbl_continuar2 = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        btn_close = new javax.swing.JPanel();
        close_icon = new javax.swing.JLabel();
        btn_cSalas = new javax.swing.JPanel();
        lbl_cSalas = new javax.swing.JLabel();
        logo_img = new javax.swing.JLabel();
        btn_cPeliculas = new javax.swing.JPanel();
        lbl_cPeliculas = new javax.swing.JLabel();
        btn_cClientes = new javax.swing.JPanel();
        lbl_cPeliculas1 = new javax.swing.JLabel();
        btn_cClientes1 = new javax.swing.JPanel();
        lbl_cPeliculas2 = new javax.swing.JLabel();
        btn_Reportes = new javax.swing.JPanel();
        lbl_cPeliculas3 = new javax.swing.JLabel();
        background_img = new javax.swing.JLabel();

        lbl_continuar1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_continuar1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_continuar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_continuar1.setText("Catálogo Salas");

        btn_continuar1.setBackground(new java.awt.Color(83, 85, 96));

        lbl_continuar2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_continuar2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_continuar2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_continuar2.setText("Catálogo Salas");

        javax.swing.GroupLayout btn_continuar1Layout = new javax.swing.GroupLayout(btn_continuar1);
        btn_continuar1.setLayout(btn_continuar1Layout);
        btn_continuar1Layout.setHorizontalGroup(
            btn_continuar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_continuar1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lbl_continuar2, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                .addContainerGap())
        );
        btn_continuar1Layout.setVerticalGroup(
            btn_continuar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_continuar1Layout.createSequentialGroup()
                .addComponent(lbl_continuar2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cinepolis App");
        setUndecorated(true);
        setResizable(false);

        content.setBackground(new java.awt.Color(47, 48, 55));
        content.setForeground(new java.awt.Color(255, 255, 255));
        content.setMinimumSize(new java.awt.Dimension(800, 600));
        content.setPreferredSize(new java.awt.Dimension(800, 600));
        content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_close.setBackground(new java.awt.Color(47, 48, 55));
        btn_close.setForeground(new java.awt.Color(47, 48, 55));
        btn_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_close.setPreferredSize(new java.awt.Dimension(20, 20));
        btn_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_closeMouseClicked(evt);
            }
        });
        btn_close.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close_icon.png"))); // NOI18N
        btn_close.add(close_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 0, 20, 20));

        content.add(btn_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 20, 20));

        btn_cSalas.setBackground(new java.awt.Color(83, 85, 96));

        lbl_cSalas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_cSalas.setForeground(new java.awt.Color(255, 255, 255));
        lbl_cSalas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_cSalas.setText("Catálogo Salas");

        javax.swing.GroupLayout btn_cSalasLayout = new javax.swing.GroupLayout(btn_cSalas);
        btn_cSalas.setLayout(btn_cSalasLayout);
        btn_cSalasLayout.setHorizontalGroup(
            btn_cSalasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_cSalas, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        btn_cSalasLayout.setVerticalGroup(
            btn_cSalasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_cSalasLayout.createSequentialGroup()
                .addComponent(lbl_cSalas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        content.add(btn_cSalas, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 300, 30));

        logo_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoCinepolis.png"))); // NOI18N
        content.add(logo_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        btn_cPeliculas.setBackground(new java.awt.Color(83, 85, 96));

        lbl_cPeliculas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_cPeliculas.setForeground(new java.awt.Color(255, 255, 255));
        lbl_cPeliculas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_cPeliculas.setText("Catálogo Películas");

        javax.swing.GroupLayout btn_cPeliculasLayout = new javax.swing.GroupLayout(btn_cPeliculas);
        btn_cPeliculas.setLayout(btn_cPeliculasLayout);
        btn_cPeliculasLayout.setHorizontalGroup(
            btn_cPeliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_cPeliculas, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        btn_cPeliculasLayout.setVerticalGroup(
            btn_cPeliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_cPeliculasLayout.createSequentialGroup()
                .addComponent(lbl_cPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        content.add(btn_cPeliculas, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 300, 30));

        btn_cClientes.setBackground(new java.awt.Color(83, 85, 96));

        lbl_cPeliculas1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_cPeliculas1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_cPeliculas1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_cPeliculas1.setText("Catálogo Clientes");

        javax.swing.GroupLayout btn_cClientesLayout = new javax.swing.GroupLayout(btn_cClientes);
        btn_cClientes.setLayout(btn_cClientesLayout);
        btn_cClientesLayout.setHorizontalGroup(
            btn_cClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_cPeliculas1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        btn_cClientesLayout.setVerticalGroup(
            btn_cClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_cClientesLayout.createSequentialGroup()
                .addComponent(lbl_cPeliculas1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        content.add(btn_cClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 300, 30));

        btn_cClientes1.setBackground(new java.awt.Color(83, 85, 96));

        lbl_cPeliculas2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_cPeliculas2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_cPeliculas2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_cPeliculas2.setText("Catálogo Funciones");

        javax.swing.GroupLayout btn_cClientes1Layout = new javax.swing.GroupLayout(btn_cClientes1);
        btn_cClientes1.setLayout(btn_cClientes1Layout);
        btn_cClientes1Layout.setHorizontalGroup(
            btn_cClientes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_cPeliculas2, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        btn_cClientes1Layout.setVerticalGroup(
            btn_cClientes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_cClientes1Layout.createSequentialGroup()
                .addComponent(lbl_cPeliculas2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        content.add(btn_cClientes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, 300, 30));

        btn_Reportes.setBackground(new java.awt.Color(83, 85, 96));

        lbl_cPeliculas3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_cPeliculas3.setForeground(new java.awt.Color(255, 255, 255));
        lbl_cPeliculas3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_cPeliculas3.setText("Reportes");

        javax.swing.GroupLayout btn_ReportesLayout = new javax.swing.GroupLayout(btn_Reportes);
        btn_Reportes.setLayout(btn_ReportesLayout);
        btn_ReportesLayout.setHorizontalGroup(
            btn_ReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_cPeliculas3, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        btn_ReportesLayout.setVerticalGroup(
            btn_ReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_ReportesLayout.createSequentialGroup()
                .addComponent(lbl_cPeliculas3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        content.add(btn_Reportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 450, 300, 30));

        background_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.png"))); // NOI18N
        background_img.setMaximumSize(new java.awt.Dimension(815, 600));
        background_img.setPreferredSize(new java.awt.Dimension(815, 600));
        content.add(background_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseClicked
        dispose();
    }//GEN-LAST:event_btn_closeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCatálogoSalas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCatálogoSalas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCatálogoSalas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCatálogoSalas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCatálogoSalas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background_img;
    private javax.swing.JPanel btn_Reportes;
    private javax.swing.JPanel btn_cClientes;
    private javax.swing.JPanel btn_cClientes1;
    private javax.swing.JPanel btn_cPeliculas;
    private javax.swing.JPanel btn_cSalas;
    private javax.swing.JPanel btn_close;
    private javax.swing.JPanel btn_continuar1;
    private javax.swing.JLabel close_icon;
    private javax.swing.JPanel content;
    private javax.swing.JLabel lbl_cPeliculas;
    private javax.swing.JLabel lbl_cPeliculas1;
    private javax.swing.JLabel lbl_cPeliculas2;
    private javax.swing.JLabel lbl_cPeliculas3;
    private javax.swing.JLabel lbl_cSalas;
    private javax.swing.JLabel lbl_continuar1;
    private javax.swing.JLabel lbl_continuar2;
    private javax.swing.JLabel logo_img;
    // End of variables declaration//GEN-END:variables
}
